### ISSUE TITLE
项目加载失败

### ISSUE THREAD

**Issue by lizhenzhaofirst** [dotnetlive/dotnetlive.account#2]
error  : 项目的默认 XML 命名空间必须为 MSBuild XML 命名空间。如果项目是用 MSBuild 2003 格式创建的，请将 xmlns="http://schemas.microsoft.com/developer/msbuild/2003" 添加到 <Project> 元素中。如果项目是用旧的 1.0 或 1.2 格式创建的，请将其转换为 MSBuild 2003 格式。

**Comment by dukecheng** [comment]
@lizhenzhaofirst 请仔细[阅读DNL项目文档](http://docs.dotnet.live/)
DNL项目基于.NET Core RC4版本开发， 必须要使用VS2017 RC3版本往上.
